name: CI
on:
  push:
    branches:
    - main
  pull_request:
  # PRs into any branch
jobs:
  build:
    name: Lint / Test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install node_modules
        run: yarn install --froze-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
